name: Build, Lint and Test
on: push
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Biome
        run: npx biome ci .

      - name: Run cspell
        run: npx cspell "**/*.{ts,js,mjs}" --no-progress

      - name: Build
        run: npm run build

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Run Tests
        run: npm run test
